//
// Created by bantdit on 1/8/19.
//

#ifndef ENTTX_UPDATESTAGES_H
#define ENTTX_UPDATESTAGES_H

enum UPDATE_STAGES {
    EARLY_UPDATE_STAGE = 0,
    LATE_UPDATE_STAGE = 1,
    LAST_STAGE = LATE_UPDATE_STAGE,
    STAGE_COUNT = LATE_UPDATE_STAGE + 1
};

#endif //ENTTX_UPDATESTAGES_H
